package lk.srilankannews.analytics;

public enum AnalyticsEventType {
    PAGE_VIEW,
    ARTICLE_VIEW,
    STORY_VIEW,
    SOURCE_VIEW,
    CATEGORY_VIEW,
    SEARCH_VIEW,
    SEARCH_RESULT_CLICK,
    FOR_YOU_VIEW,
    FOR_YOU_CLICK,
    TRENDING_VIEW,
    TRENDING_CLICK,
    BOOKMARK_CREATED,
    BOOKMARK_REMOVED,
    FOLLOW_CREATED,
    FOLLOW_REMOVED,
    NOTIFICATION_CENTER_VIEW,
    SEARCH_EXECUTED,
    ASK_STORY_COMPLETED,
    NOTIFICATION_CREATED,
    NOTIFICATION_READ,
    NOTIFICATION_EMAIL_SENT,
    NOTIFICATION_EMAIL_FAILED
}
